/**
 * All Action Keys will go here
 */
const ACTION_KEYS = {
  PROPERTY_ADD_REQUEST: 'PROPERTY_ADD_REQUEST',
  PROPERTY_ADD_SUCCESS: 'PROPERTY_ADD_SUCCESS',
  PROPERTY_ADD_ERROR: 'PROPERTY_ADD_ERROR',

  REGSITER_TYPE: 'REGISTER_TYPE',
  STORE_AUTH: 'STORE_AUTH',
  DOMAIN_SKILLS_LIST_REQUEST: 'DOMAIL_SKILLS_LIST_REQUEST',
  DOMAIN_SKILLS_LIST_SUCCESS: 'DOMAIL_SKILLS_LIST_SUCCESS',
  DOMAIN_SKILLS_LIST_FAILURE: 'DOMAIL_SKILLS_LIST_FAILURE',
  SUGGESTED_SERVICE_REQUEST: 'SUGGESTED_SERVICE_REQUEST',
  SUGGESTED_SERVICE_SUCCESS: 'SUGGESTED_SERVICE_SUCCESS',
  SUGGESTED_SERVICE_FAILURE: 'SUGGESTED_SERVICE_FAILURE',
  WINDOWLAYOUT: 'WINDOWLAYOUT',
  KYCSTEP1: 'KYCSTEP1',
  KYCSTEP2: 'KYCSTEP2',
  KYCSTEP4: 'KYCSTEP4',
  PROFESSIONAL_DETAILS: 'PROFESSIONAL_DETAILS',
  MENTOR_HEADING: 'MENTOR_HEADING',
  STUDENT_HEADING: 'STUDENT_HEADING',
  SERVICES_HEADING: 'SERVICES_HEADING',
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',
  SIGN_UP: 'SIGN_UP',
  LOG_IN: 'LOG_IN',
  GET_MENTOR: 'GET_MENTOR',
  SET_MENTORS: 'SET_MENTORS',
  GET_STUDENT: 'GET_STUDENT',
  SET_STUDENTS: 'SET_STUDENTSS',
  SET_STUDENT_PURCHASES: 'SET_STUDENT_PURCHASES',
  SET_MENTOR_SALES: 'SET_MENTOR_SALES',

  ONE_ON_ONE: 'ONE_ON_ONE',
  WORKSHOP: 'WORKSHOP',
  COURSES: 'COURSES',
  TEXT_QUERY: 'TEXT_QUERY',
  PACKAGES: 'PACKAGES',
}

export default ACTION_KEYS
